### ISSUE TITLE
Not online

### ISSUE THREAD

**Issue by rpbrown3622** [ItsMeBrille/MMM-MinecraftServer#1]
I configured the module and it just says the server is offline even thought it is currently running on my other raspberry pi.
I am running bedrock on my raspberry pi 3 and the magic mirror is running on a raspberry pi 4.
I used the api from Minecraft Server Status  of https://api.mcsrvstat.us/bedrock/3/MYEXTERNALIPADDRESS. I entered in my external IP address and it returns with the correct info stating that it is online and pings in a web browser but in the magic mirror it still says offline. 

Im sorry if this isnt making much sense, I dont know how to exactly explain this.

Thanks for any help.

**Comment by ItsMeBrille** [comment]
Thanks for letting me know. I have not tested it with bedrock hosting.
However, it might work if you change the URL from `https://api.mcsrvstat.us/3/` to `https://api.mcsrvstat.us/bedrock/3/` at line `28` in the .js file in the module files.

Please let me know if you get it to work. If that's the case, I can create an easy version selector.

**Comment by rpbrown3622** [comment]
This is what is on my config file
{
  module: "MMM-MinecraftServer",
  position: "top_right",
  config: {
    ip: "d6d4xyhgr8y.d.firewalla.org", // server ip (required)
    title: "B&D Minecraft Server", // display title
    hidePlayers: false, // Hide player list
    maxPlayers: 5, // Max players to show in list
    hideInfo: false, // Hide bottom info (ip, version)
    updateInterval: 5, // update interval in minutes
  }
},
This is what I have for the .js file
Module.register("MMM-MinecraftServer", {
  defaults: {
    ip: "d6d4xyhgr8y.d.firewalla.org", // Default Minecraft server IP
    title: "Minecraft Server",
    hidePlayers: false, // Hide player list
    maxPlayers: 10, // Max players to show in list
    hideInfo: false, // Hide bottom info (ip, version)
    updateInterval: 5, // Default update interval (5 minutes)
  },

  players: [],
  info: [],

  start() {
    // Log module start
    Log.info(`Starting module: ${this.name}`);
    this.getPlayers();
    setInterval(() => {
      this.getPlayers();
    }, this.config.updateInterval * 60000);
  },

  getStyles() {
    return ["MMM-MinecraftServer.css"]; // Add your CSS file here if needed
  },

  getPlayers() {
    fetch(`https://api.mcsrvstat.us/bedrock/3/${this.config.ip}`)
      .then((response) => response.json())
      .then((data) => {
        if (data.players && data.players.list) {
          this.players = data.players.list;
        }

        this.info.ping = data.debug.ping;

        if (this.info.ping) {
          this.info.motd = data.motd.html[0];
          this.info.hostname = data.hostname;
          this.info.port = data.port;
          this.info.version = data.version;
        }
        this.updateDom();
      })
      .catch((error) => {
        console.error("Error fetching Minecraft server data:", error);
      });
  },

  getDom() {
    // Wrapper
    const wrapper = document.createElement("div");
    wrapper.className = "minecraft-card";

    // Title
    const title = document.createElement("h1");
    title.className = "title";
    title.innerHTML = this.config.title;
    wrapper.appendChild(title);

    // Server not available
    if (!this.info.ping) {

      const info = document.createElement("span");
      info.className = "motd";
      info.innerHTML = `Server offline`;
      wrapper.appendChild(info);
    } else {
      // MOTD
      const motd = document.createElement("span");
      motd.className = "motd";
      motd.innerHTML = this.info.motd || "";
      wrapper.appendChild(motd);
    }



    // Players
    if (!this.config.hidePlayers) {
      const playerTable = document.createElement("table");
      playerTable.className = "players";

      this.players.slice(0, this.config.maxPlayers).forEach((player) => {
        const playerRow = document.createElement("tr");

        const avatarCell = document.createElement("td");
        const avatar = document.createElement("img");
        avatar.className = "player-avatar";
        avatar.src = `https://mc-heads.net/avatar/${player.uuid}/64`;
        avatarCell.appendChild(avatar);
        playerRow.appendChild(avatarCell);

        const nameCell = document.createElement("td");
        const playerName = document.createElement("span");
        playerName.className = "player-name";

        playerName.innerHTML = (player.name.length < 16) ? player.name : player.name.substring(0, 14) + "...";
        nameCell.appendChild(playerName);
        playerRow.appendChild(nameCell);

        const connectionCell = document.createElement("td");
        const connectionBars = document.createElement("div");
        connectionBars.className = "connection-bars";
        connectionCell.appendChild(connectionBars);
        playerRow.appendChild(connectionCell);

        playerTable.appendChild(playerRow);
      });
      wrapper.appendChild(playerTable);
    }

    // Info
    if (!this.config.hideInfo) {
      const info = document.createElement("span");
      info.className = "info";
      info.innerHTML = `${this.config.ip}${this.info.version ? " - " + this.info.version : ""}`;
      wrapper.appendChild(info);
    }

    return wrapper;
  },
});

**Comment by ItsMeBrille** [comment]
Thank you for providing your code. I have updated the repo now with the option to display bedrock servers. Please close this issue and leave a ⭐ if you like the update.

**Comment by rpbrown3622** [comment]
EXCELLENT!!!! It works now. Thank you so very much. I will close this and leave a star!!!!

**Comment by rpbrown3622** [comment]
so I made the changes and updated the mod. So it sees my bedrock server and says its online but when I go on the minecraft server  it doesnt show me online. Isnt it suppose to list everyone who is currently playing on the server?

**Comment by ItsMeBrille** [comment]
> so I made the changes and updated the mod. So it sees my bedrock server and says its online but when I go on the minecraft server it doesnt show me online. Isnt it suppose to list everyone who is currently playing on the server?

In my experience, the list is only available for some servers. I don't know what's happening, but it doesn't work on some servers. I have no list of what providers support it. It's not my module, but the API that is the bottleneck for this issue.
